export const FLOORING_MEGA_MENU = [
  {
    title: "Floor tiles by Look",
    itemType: "look",
    items: [
      { label: "Brick Look", href: "/product-category/floor-tiles/brick", image: "/images/menu-look/brick.png" },
      { label: "Wood", href: "/product-category/floor-tiles/wood-design", image: "/images/menu-look/wood.png" },
      { label: "Stone", href: "/product-category/floor-tiles/stone-design", image: "/images/menu-look/stone.png" },
      { label: "Marble", href: "/product-category/floor-tiles/marble-design", image: "/images/menu-look/marble.png" },
      { label: "Cement", href: "/product-category/floor-tiles/concrete-cement-design", image: "/images/menu-look/cement.png" },
      { label: "Terrazzo", href: "/product-category/floor-tiles/terrazzo-design", image: "/images/menu-look/terrazzo.png" },
      { label: "Patterned", href: "/product-category/floor-tiles/patterned", image: "/images/menu-look/patterned.png" },
      { label: "Minimalistic", href: "/product-category/floor-tiles/minimalist-design", image: "/images/menu-look/minimalist.png" },
      { label: "Handmade", href: "/product-category/floor-tiles/decor-tiles", image: "/images/menu-look/handmade.png" },
    ],
  },
  {
    title: "Floor tiles by Colour",
    itemType: "colour",
    items: [
      { label: "Grey", href: "/product-category/floor-tiles?colours=grey", image: "/images/menu-colour/grey.png" },
      // { label: "Black", href: "/product-category/floor-tiles?colours=black", swatch: "bg-black" },
      { label: "Green", href: "/product-category/floor-tiles?colours=green", image: "/images/menu-colour/green.png" },
      { label: "Blue", href: "/product-category/floor-tiles?colours=blue", image: "/images/menu-colour/blue.png" },
      { label: "Pink", href: "/product-category/floor-tiles?colours=pink", image: "/images/menu-colour/pink.png" },
      { label: "Brown", href: "/product-category/floor-tiles?colours=brown", image: "/images/menu-colour/brown.png" },
      // { label: "Beige", href: "/product-category/floor-tiles?colours=beige", swatch: "bg-[#d4b896]" },
      // { label: "Cream", href: "/product-category/floor-tiles?colours=cream", swatch: "bg-[#f5f5dc] border border-gray-300" },
      { label: "White", href: "/product-category/floor-tiles?colours=white", image: "/images/menu-colour/white.png" },
      { label: "Red", href: "/product-category/floor-tiles?colours=red", image: "/images/menu-colour/red.png" },
      // { label: "Sand", href: "/product-category/floor-tiles?colours=sand", swatch: "bg-[#c2b280]" },
      { label: "Gold", href: "/product-category/floor-tiles?colours=gold", image: "/images/menu-colour/gold.png" },
      // { label: "Purple", href: "/product-category/floor-tiles?colours=purple", swatch: "bg-purple-600" },
      { label: "Yellow", href: "/product-category/floor-tiles?colours=yellow", image: "/images/menu-colour/yellow.png" },
      // { label: "Orange", href: "/product-category/floor-tiles?colours=orange", swatch: "bg-orange-500" },
      // { label: "Multicolour", href: "/product-category/floor-tiles?colours=multicolour", image: "/images/menu-colour/multicolour.png" },
    ],
  },
  {
    title: "Floor tiles by Size",
    itemType: "size",
    items: [
      { label: "", href: "/product-category/floor-tiles?sizes=1080%20x%201080", dimension: "1080×1080" },
      { label: "", href: "/product-category/floor-tiles?sizes=600%20x%20600", dimension: "600×600" },
      { label: "", href: "/product-category/floor-tiles?sizes=800%20x%20800", dimension: "800×800" },
      { label: "", href: "/product-category/floor-tiles?sizes=1200%20x%201200", dimension: "1200×1200" },
      { label: "", href: "/product-category/floor-tiles?sizes=600%20x%201200", dimension: "600×1200" },
      { label: "", href: "/product-category/floor-tiles?sizes=1600%20x%20800", dimension: "1600×800" },
      { label: "", href: "/product-category/floor-tiles?sizes=1000%20x%201000", dimension: "1000×1000" },
      { label: "Smaller Sizes", href: "/product-category/floor-tiles", dimension: "Small" },
    ],
  },
  {
    title: "Floor tiles by Space",
    itemType: "icon",
    items: [
      { label: "Kitchen", href: "/product-category/floor-tiles/kitchen", image: "/images/needs/kitchen.jpg" },
      { label: "Bathroom", href: "/product-category/floor-tiles/bathroom", image: "/images/needs/bathrooms.jpg" },
      { label: "Indoor", href: "/product-category/floor-tiles/indoor", image: "/images/needs/indoor.jpg" },
      {
        label: "Outdoor / Slip Resistant",
        href: "/product-category/floor-tiles/outdoor",
        image: "/images/needs/outdoors.jpg",
      },
      { label: "Pool", href: "/product-category/floor-tiles/pool", image: "/images/needs/pool.jpg" },
      { label: "Commercial", href: "/product-category/floor-tiles/commercial", image: "/images/needs/commercial.jpg" },
      { label: "Countertop", href: "/product-category/floor-tiles/countertop", image: "/images/needs/counters.jpg" },
    ],
  },
  {
    title: "Installation Needs",
    itemType: "icon",
    items: [
      { label: "Adhesives", href: "/product-category/floor-tiles/adhesives", image: "/images/needs/adhesives.jpg" },
      { label: "Grouts", href: "/product-category/floor-tiles/grouts", image: "/images/needs/grouts.jpg" },
      { label: "Trims and Edges", href: "/product-category/floor-tiles/skirtings", image: "/images/needs/trims%20and%20edges.jpg" },
      { label: "Tools and Spacers", href: "/product-category/floor-tiles/spacers", image: "/images/needs/tools%20and%20spacers.jpg" },
      { label: "Cleaning Products and Chemicals", href: "/product-category/floor-tiles/cleaning", image: "/images/needs/cleaning.jpg" },
    ],
  },
];
