
import {
  Bath,
  CookingPot,
  Sun,
  TreePine,
  Home,
  Waves,
  Building2,
  PanelTop,
  Package,
  Droplets,
  SprayCan,
  LayoutGrid,
} from "lucide-react";

export const FLOORING_MEGA_MENU = [
  {
    title: "Floor tiles by look",
    itemType: "look",
    items: [
      { label: "Brick Look", href: "/product-category/flooring/brick", swatch: "bg-gradient-to-br from-red-900 via-red-700 to-red-500" },
      { label: "Wood", href: "/product-category/flooring/wood-design", swatch: "bg-gradient-to-br from-amber-800 via-amber-600 to-amber-400" },
      { label: "Stone", href: "/product-category/flooring/stone-design", swatch: "bg-stone-500" },
      { label: "Marble", href: "/product-category/flooring/marble-design", swatch: "bg-gradient-to-br from-gray-200 via-white to-gray-400" },
      { label: "Cement", href: "/product-category/flooring/concrete-cement-design", swatch: "bg-gray-400" },
      { label: "Terrazzo", href: "/product-category/flooring/terrazzo-design", swatch: "bg-[radial-gradient(circle,#666_1px,transparent_1px)] bg-[length:4px_4px] bg-gray-200" },
      { label: "Patterned", href: "/product-category/flooring/patterned", swatch: "bg-[linear-gradient(45deg,#ccc_25%,transparent_25%),linear-gradient(-45deg,#ccc_25%,transparent_25%),linear-gradient(45deg,transparent_75%,#ccc_75%),linear-gradient(-45deg,transparent_75%,#ccc_75%)] bg-[length:8px_8px] bg-[position:0_0,0_4px,4px_-4px,-4px_0px] bg-gray-100" },
      { label: "Minimalistic", href: "/product-category/flooring/minimalist-design", swatch: "bg-gradient-to-br from-gray-100 to-gray-300" },
      { label: "Handmade", href: "/product-category/flooring/decor-tiles", swatch: "bg-gradient-to-br from-amber-700 via-orange-300 to-amber-900" },
    ],
  },
  {
    title: "Floor tiles by colour",
    itemType: "colour",
    items: [
      { label: "Grey", href: "/product-category/flooring/grey", swatch: "bg-gray-400" },
      { label: "Black", href: "/product-category/flooring/black", swatch: "bg-black" },
      { label: "Green", href: "/product-category/flooring/green", swatch: "bg-green-600" },
      { label: "Blue", href: "/product-category/flooring/blue", swatch: "bg-blue-600" },
      { label: "Pink", href: "/product-category/flooring/pink", swatch: "bg-pink-400" },
      { label: "Brown", href: "/product-category/flooring/brown", swatch: "bg-[#6b4423]" },
      { label: "Beige", href: "/product-category/flooring/beige", swatch: "bg-[#d4b896]" },
      { label: "Cream", href: "/product-category/flooring/cream", swatch: "bg-[#f5f5dc] border border-gray-300" },
      { label: "White", href: "/product-category/flooring/white", swatch: "bg-white border border-gray-300" },
      { label: "Red", href: "/product-category/flooring/red", swatch: "bg-red-600" },
      { label: "Sand", href: "/product-category/flooring/sand", swatch: "bg-[#c2b280]" },
      { label: "Gold", href: "/product-category/flooring/gold", swatch: "bg-[#d4af37]" },
      { label: "Purple", href: "/product-category/flooring/purple", swatch: "bg-purple-600" },
      { label: "Yellow", href: "/product-category/flooring/yellow", swatch: "bg-yellow-400" },
      { label: "Orange", href: "/product-category/flooring/orange", swatch: "bg-orange-500" },
    ],
  },
  {
    title: "Floor tiles by size",
    itemType: "size",
    items: [
      { label: "", href: "/product-category/flooring?sizes=1080%20x%201080", dimension: "1080×1080" },
      { label: "", href: "/product-category/flooring?sizes=600%20x%20600", dimension: "600×600" },
      { label: "", href: "/product-category/flooring?sizes=800%20x%20800", dimension: "800×800" },
      { label: "", href: "/product-category/flooring?sizes=1200%20x%201200", dimension: "1200×1200" },
      { label: "", href: "/product-category/flooring?sizes=600%20x%201200", dimension: "600×1200" },
      { label: "", href: "/product-category/flooring?sizes=1600%20x%20800", dimension: "1600×800" },
      { label: "", href: "/product-category/flooring?sizes=1000%20x%201000", dimension: "1000×1000" },
      { label: "Smaller Sizes", href: "/product-category/flooring", dimension: "Small" },
    ],
  },
  {
    title: "Floor tiles by space",
    itemType: "icon",
    items: [
      { label: "Kitchen", href: "/product-category/flooring/kitchen", icon: CookingPot },
      { label: "Bathroom", href: "/product-category/flooring/bathroom", icon: Bath },
      { label: "Indoor", href: "/product-category/flooring/indoor", icon: Home },
      {
        label: "Outdoor / Slip Resistant",
        href: "/product-category/flooring/outdoor",
        icon: TreePine,
        extraIcon: Sun,
      },
      { label: "Pool", href: "/product-category/flooring/pool", icon: Waves },
      { label: "Commercial", href: "/product-category/flooring/commercial", icon: Building2 },
      { label: "Countertop", href: "/product-category/flooring/countertop", icon: PanelTop },
    ],
  },
  {
    title: "Installation Needs",
    itemType: "icon",
    items: [
      { label: "Adhesives", href: "/product-category/flooring/adhesives", icon: Package },
      { label: "Grouts", href: "/product-category/flooring/grouts", icon: Droplets },
      { label: "Trims and Edges", href: "/product-category/flooring/skirtings", icon: PanelTop },
      { label: "Tools and Spacers", href: "/product-category/flooring/spacers", icon: LayoutGrid },
      { label: "Cleaning Products and Chemicals", href: "/product-category/flooring/cleaning", icon: SprayCan },
    ],
  },
];
