import {
  Bath,
  CookingPot,
  TreePine,
  Home,
  Waves,
  Building2,
  PanelTop,
  Package,
  Droplets,
  SprayCan,
  LayoutGrid,
} from "lucide-react";

const BASE = "/product-category/tiles/wall-tiles";

export const WALL_TILES_MEGA_MENU = [
  {
    title: "Wall tiles by Look",
    itemType: "look",
    items: [
      { label: "Brick Look", href: `${BASE}/brick-wall-tiles`, image: "/images/menu-look/brick.png" },
      { label: "Wood", href: `${BASE}/wood-design-wall-tiles`, image: "/images/menu-look/wood.png" },
      { label: "Stone", href: `${BASE}/stone`, image: "/images/menu-look/stone.png" },
      { label: "Marble", href: `${BASE}/marble`, image: "/images/menu-look/marble.png" },
      { label: "Cement", href: `${BASE}/concrete-design-wall-tiles`, image: "/images/menu-look/cement.png" },
      { label: "Terrazzo", href: `${BASE}/terrazo-design`, image: "/images/menu-look/terrazzo.png" },
      { label: "Patterned", href: `${BASE}/patterned-wall-tiles`, image: "/images/menu-look/patterned.png" },
      { label: "Minimalistic", href: `${BASE}/minimalist`, image: "/images/menu-look/minimalist.png" },
      { label: "Handmade", href: `${BASE}/decor-tiles-wall-tiles`, image: "/images/menu-look/handmade.png" },
      { label: "Metal Look", href: `${BASE}/metallic-look-wall-tiles`, image: "/images/menu-look/metal.png" },
      { label: "Subway", href: `${BASE}/subway-tiles`, image: "/images/menu-look/subway.png" },
      { label: "Smalls", href: `${BASE}/monocolour-wall-tiles`, image: "/images/menu-look/smalls.png" },
      { label: "Fluted", href: `${BASE}/fluted`, image: "/images/menu-look/fluted.png" },
      { label: "Kit Kat", href: `${BASE}/kit-kat-wall-tiles`, image: "/images/menu-look/kit-kat.png" },
      { label: "Hexagon", href: `${BASE}/hexagon-tiles-wall-tiles`, image: "/images/menu-look/hexagon.png" },
      { label: "Relief", href: `${BASE}/relief`, image: "/images/menu-look/relief.png" },
    ],
  },
  {
    title: "Wall tiles by Colour",
    itemType: "colour",
    items: [
      { label: "Grey", href: `${BASE}?colours=grey`, image: "/images/menu-colour/grey.png" },
      // { label: "Black", href: `${BASE}?colours=black`, swatch: "bg-black" },
      { label: "Green", href: `${BASE}?colours=green`, image: "/images/menu-colour/green.png" },
      { label: "Blue", href: `${BASE}?colours=blue`, image: "/images/menu-colour/blue.png" },
      { label: "Pink", href: `${BASE}?colours=pink`, image: "/images/menu-colour/pink.png" },
      { label: "Brown", href: `${BASE}?colours=brown`, image: "/images/menu-colour/brown.png" },
      // { label: "Beige", href: `${BASE}?colours=beige`, swatch: "bg-[#d4b896]" },
      // { label: "Cream", href: `${BASE}?colours=cream`, swatch: "bg-[#f5f5dc] border border-gray-300" },
      { label: "White", href: `${BASE}?colours=white`, image: "/images/menu-colour/white.png" },
      { label: "Red", href: `${BASE}?colours=red`, image: "/images/menu-colour/red.png" },
      // { label: "Sand", href: `${BASE}?colours=sand`, swatch: "bg-[#c2b280]" },
      { label: "Gold", href: `${BASE}?colours=gold`, image: "/images/menu-colour/matellic.png" },
      // { label: "Purple", href: `${BASE}?colours=purple`, swatch: "bg-purple-600" },
      { label: "Yellow", href: `${BASE}?colours=yellow`, image: "/images/menu-colour/yellow.png" },
      // { label: "Orange", href: `${BASE}?colours=orange`, swatch: "bg-orange-500" },
      // { label: "Multicolour", href: `${BASE}?colours=multicolour`, image: "/images/menu-colour/multicolour.png" },
    ],
  },
  {
    title: "Wall tiles by Size",
    itemType: "size",
    items: [
      { label: "", href: `${BASE}?sizes=1080%20x%201080`, dimension: "1080×1080" },
      { label: "", href: `${BASE}?sizes=600%20x%20600`, dimension: "600×600" },
      { label: "", href: `${BASE}?sizes=800%20x%20800`, dimension: "800×800" },
      { label: "", href: `${BASE}?sizes=1200%20x%20200`, dimension: "1200×200" },
      { label: "", href: `${BASE}?sizes=600%20x%201200`, dimension: "600×1200" },
      { label: "", href: `${BASE}?sizes=1600%20x%20800`, dimension: "1600×800" },
      { label: "", href: `${BASE}?sizes=1000%20x%201000`, dimension: "1000×1000" },
      { label: "Smaller Sizes", href: BASE, dimension: "Small" },
    ],
  },
  {
    title: "Wall tiles by Space",
    itemType: "icon",
    items: [
      { label: "Kitchen", href: `${BASE}/kitchen`, icon: CookingPot },
      { label: "Bathroom", href: `${BASE}/bathroom`, icon: Bath },
      { label: "Indoor", href: `${BASE}/indoor`, icon: Home },
      { label: "Outdoor Walls", href: `${BASE}/outdoor-walls`, icon: TreePine },
      { label: "Pool", href: `${BASE}/pool`, icon: Waves },
      { label: "Commercial", href: `${BASE}/commercial`, icon: Building2 },
      { label: "Countertop", href: `${BASE}/countertop`, icon: PanelTop },
    ],
  },
  {
    title: "Installation Needs",
    itemType: "icon",
    items: [
      { label: "Adhesives", href: "/product-category/tiles/accessories-tools/tile-adhesive-porcelain", icon: Package },
      { label: "Grouts", href: "/product-category/tiles/accessories-tools/grout", icon: Droplets },
      { label: "Trims and Edges", href: "/product-category/tiles/accessories-tools/trim", icon: PanelTop },
      { label: "Tools and Spacers", href: "/product-category/tiles/accessories-tools/tile-spacer", icon: LayoutGrid },
      { label: "Cleaning Products and Chemicals", href: "/product-category/tiles/accessories-tools/cleaning-product", icon: SprayCan },
    ],
  },
];
