const BASE = "/product-category/tiles/wall-tiles";

export const WALL_TILES_MEGA_MENU = [
  {
    title: "Wall tiles by Look",
    itemType: "look",
    items: [
      { label: "Brick Look", href: `${BASE}/brick-wall-tiles`, image: "/images/menu-look/brick.png" },
      { label: "Wood", href: `${BASE}/wood-design-wall-tiles`, image: "/images/menu-look/wood.png" },
      { label: "Stone", href: `${BASE}/stone`, image: "/images/menu-look/stone.png" },
      { label: "Marble", href: `${BASE}/marble`, image: "/images/menu-look/marble.png" },
      { label: "Cement", href: `${BASE}/concrete-design-wall-tiles`, image: "/images/menu-look/cement.png" },
      { label: "Terrazzo", href: `${BASE}/terrazo-design`, image: "/images/menu-look/terrazzo.png" },
      { label: "Patterned", href: `${BASE}/patterned-wall-tiles`, image: "/images/menu-look/patterned.png" },
      { label: "Minimalistic", href: `${BASE}/minimalist`, image: "/images/menu-look/minimalist.png" },
      { label: "Handmade", href: `${BASE}/decor-tiles-wall-tiles`, image: "/images/menu-look/handmade.png" },
      { label: "Metal Look", href: `${BASE}/metallic-look-wall-tiles`, image: "/images/menu-look/metal.png" },
      { label: "Subway", href: `${BASE}/subway-tiles`, image: "/images/menu-look/subway.png" },
      { label: "Smalls", href: `${BASE}/monocolour-wall-tiles`, image: "/images/menu-look/smalls.png" },
      { label: "Fluted", href: `${BASE}/fluted`, image: "/images/menu-look/fluted.png" },
      { label: "Kit Kat", href: `${BASE}/kit-kat-wall-tiles`, image: "/images/menu-look/kit-kat.png" },
      { label: "Hexagon", href: `${BASE}/hexagon-tiles-wall-tiles`, image: "/images/menu-look/hexagon.png" },
      { label: "Relief", href: `${BASE}/relief`, image: "/images/menu-look/relief.png" },
    ],
  },
  {
    title: "Wall tiles by Colour",
    itemType: "colour",
    items: [
      { label: "Grey", href: `${BASE}?colours=grey`, image: "/images/menu-colour/grey.png" },
      // { label: "Black", href: `${BASE}?colours=black`, swatch: "bg-black" },
      { label: "Green", href: `${BASE}?colours=green`, image: "/images/menu-colour/green.png" },
      { label: "Blue", href: `${BASE}?colours=blue`, image: "/images/menu-colour/blue.png" },
      { label: "Pink", href: `${BASE}?colours=pink`, image: "/images/menu-colour/pink.png" },
      { label: "Brown", href: `${BASE}?colours=brown`, image: "/images/menu-colour/brown.png" },
      // { label: "Beige", href: `${BASE}?colours=beige`, swatch: "bg-[#d4b896]" },
      // { label: "Cream", href: `${BASE}?colours=cream`, swatch: "bg-[#f5f5dc] border border-gray-300" },
      { label: "White", href: `${BASE}?colours=white`, image: "/images/menu-colour/white.png" },
      { label: "Red", href: `${BASE}?colours=red`, image: "/images/menu-colour/red.png" },
      // { label: "Sand", href: `${BASE}?colours=sand`, swatch: "bg-[#c2b280]" },
      { label: "Gold", href: `${BASE}?colours=gold`, image: "/images/menu-colour/gold.png" },
      // { label: "Purple", href: `${BASE}?colours=purple`, swatch: "bg-purple-600" },
      { label: "Yellow", href: `${BASE}?colours=yellow`, image: "/images/menu-colour/yellow.png" },
      // { label: "Orange", href: `${BASE}?colours=orange`, swatch: "bg-orange-500" },
      // { label: "Multicolour", href: `${BASE}?colours=multicolour`, image: "/images/menu-colour/multicolour.png" },
    ],
  },
  {
    title: "Wall tiles by Size",
    itemType: "size",
    items: [
      { label: "", href: `${BASE}?sizes=1080%20x%201080`, dimension: "1080×1080" },
      { label: "", href: `${BASE}?sizes=600%20x%20600`, dimension: "600×600" },
      { label: "", href: `${BASE}?sizes=800%20x%20800`, dimension: "800×800" },
      { label: "", href: `${BASE}?sizes=1200%20x%20200`, dimension: "1200×200" },
      { label: "", href: `${BASE}?sizes=600%20x%201200`, dimension: "600×1200" },
      { label: "", href: `${BASE}?sizes=1600%20x%20800`, dimension: "1600×800" },
      { label: "", href: `${BASE}?sizes=1000%20x%201000`, dimension: "1000×1000" },
      { label: "Smaller Sizes", href: BASE, dimension: "Small" },
    ],
  },
  {
    title: "Wall tiles by Space",
    itemType: "icon",
    items: [
      { label: "Kitchen", href: `${BASE}?space=Kitchen`, image: "/images/needs/kitchen.jpg" },
      { label: "Bathroom", href: `${BASE}?space=Bathrooms`, image: "/images/needs/bathrooms.jpg" },
      { label: "Indoor", href: `${BASE}?space=Indoor`, image: "/images/needs/indoor.jpg" },
      { label: "Outdoor Walls", href: `${BASE}?space=Outdoor%20Walls`, image: "/images/needs/outdoors.jpg" },
      { label: "Pool", href: `${BASE}?space=Pool`, image: "/images/needs/pool.jpg" },
      { label: "Commercial", href: `${BASE}?space=Commercial`, image: "/images/needs/commercial.jpg" },
      { label: "Countertop", href: `${BASE}?space=Countertop`, image: "/images/needs/counters.jpg" },
    ],
  },
  {
    title: "Installation Needs",
    itemType: "icon",
    items: [
      { label: "Adhesives", href: `${BASE}?installation_needs=Adhesives`, image: "/images/needs/adhesives.jpg" },
      { label: "Grouts", href: `${BASE}?installation_needs=Grouts`, image: "/images/needs/grouts.jpg" },
      { label: "Trims and Edges", href: `${BASE}?installation_needs=Trims%20and%20Edges`, image: "/images/needs/trims%20and%20edges.jpg" },
      { label: "Tools and Spacers", href: `${BASE}?installation_needs=Tools%20and%20Spacers`, image: "/images/needs/tools%20and%20spacers.jpg" },
      { label: "Cleaning Products and Chemicals", href: `${BASE}?installation_needs=Cleaning%20Products%20and%20Chemicals`, image: "/images/needs/cleaning.jpg" },
    ],
  },
];
